"""Remove bottler columns

Revision ID: 01f980da95da
Revises: c8413fb71e09
Create Date: 2023-09-10 19:24:58.061742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01f980da95da'
down_revision = 'c8413fb71e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bottler')
    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.drop_column('bottler_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bottler_id', mysql.VARCHAR(length=36), nullable=True))

    op.create_table('bottler',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=65), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('region_1', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('region_2', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='bottler_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
