"""Added has_image to bottle table

Revision ID: 09251ee1c984
Revises: ae894c34dcca
Create Date: 2023-02-11 13:55:32.334340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09251ee1c984'
down_revision = 'ae894c34dcca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_image', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.drop_column('has_image')

    # ### end Alembic commands ###
