"""make foreign keys non-nullable

Revision ID: 3649eef66fce
Revises: c519b1492a88
Create Date: 2023-02-04 01:13:22.626028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3649eef66fce'
down_revision = 'c519b1492a88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.alter_column('distillery_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('distillery', schema=None) as batch_op:
        batch_op.alter_column('region_1',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('region_2',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distillery', schema=None) as batch_op:
        batch_op.alter_column('region_2',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('region_1',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('distillery_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###
