"""Created bottle and distillery tables

Revision ID: 80567db94182
Revises: 1d381daabe28
Create Date: 2023-02-03 21:31:18.011294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80567db94182'
down_revision = '1d381daabe28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distillery',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=65), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('region_1', sa.String(length=36), nullable=True),
    sa.Column('region_2', sa.String(length=36), nullable=True),
    sa.Column('url', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bottle',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('abv', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('stars', sa.Float(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_killed', sa.DateTime(), nullable=True),
    sa.Column('distillery_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['distillery_id'], ['distillery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bottle')
    op.drop_table('distillery')
    # ### end Alembic commands ###
