"""Change image column

Revision ID: 10c30d9a702e
Revises: 77ce5ce48590
Create Date: 2023-02-24 21:27:56.675365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10c30d9a702e'
down_revision = '77ce5ce48590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_count', sa.Integer(), nullable=True))
        batch_op.drop_column('has_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_image', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('image_count')

    # ### end Alembic commands ###
