"""Add bottler column to bottle table

Revision ID: 199e2dc9ea1f
Revises: 33101a6ed7be
Create Date: 2023-09-04 13:48:50.686201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199e2dc9ea1f'
down_revision = '33101a6ed7be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bottler_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.drop_column('bottler_id')

    # ### end Alembic commands ###
