"""fix bottle_image bottle_id nullable

Revision ID: 27e06a9024f8
Revises: 19f70e8be239
Create Date: 2025-07-27 16:59:31.374876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27e06a9024f8'
down_revision = '19f70e8be239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle_image', schema=None) as batch_op:
        batch_op.alter_column('bottle_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle_image', schema=None) as batch_op:
        batch_op.alter_column('bottle_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###
