"""add glen_scan_count to user

Revision ID: 39513633ce1c
Revises: c4f910134435
Create Date: 2026-06-09 19:30:21.451233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39513633ce1c'
down_revision = 'c4f910134435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('glen_scan_count', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('glen_scan_count')

    # ### end Alembic commands ###
