"""Update user login table structure

Revision ID: 6c7916b59f10
Revises: 65912bda5455
Create Date: 2025-01-22 04:19:07.004342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7916b59f10'
down_revision = '65912bda5455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_login',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('login_date', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'login_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_login')
    # ### end Alembic commands ###
