"""add last_login_at and warned_at to user

Revision ID: 6e2b70a98128
Revises: 6b10feb1f342
Create Date: 2026-05-11 19:02:47.629812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2b70a98128'
down_revision = '6b10feb1f342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('warned_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('warned_at')
        batch_op.drop_column('last_login_at')

    # ### end Alembic commands ###
