"""Added date_opened column

Revision ID: 77ce5ce48590
Revises: 4d9844491681
Create Date: 2023-02-22 20:42:11.582236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ce5ce48590'
down_revision = '4d9844491681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_opened', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.drop_column('date_opened')

    # ### end Alembic commands ###
