"""Add new bottler table and columns

Revision ID: 78a71df17691
Revises: 01f980da95da
Create Date: 2023-09-10 19:38:30.825797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a71df17691'
down_revision = '01f980da95da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bottler',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=65), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('region_1', sa.String(length=36), nullable=False),
    sa.Column('region_2', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bottler_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'bottler', ['bottler_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bottler_id')

    op.drop_table('bottler')
    # ### end Alembic commands ###
