"""add is_pro to user

Revision ID: 7be8efebe070
Revises: 7ccc52f60419
Create Date: 2026-06-06 17:09:12.436121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be8efebe070'
down_revision = '7ccc52f60419'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pro', sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_pro')

    # ### end Alembic commands ###
