"""add is_active to user

Revision ID: 7ccc52f60419
Revises: 1af6adc6878a
Create Date: 2026-06-06 15:30:17.173316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ccc52f60419'
down_revision = '1af6adc6878a'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))

    op.execute("UPDATE user SET is_active = 1 WHERE is_active = 0")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
