"""Increased some fields

Revision ID: 96f9ba30b7e5
Revises: 10c30d9a702e
Create Date: 2023-02-27 18:26:22.743845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96f9ba30b7e5'
down_revision = '10c30d9a702e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('url',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###
