"""Add personal_note column to bottle table

Revision ID: ae075b14c2b8
Revises: b86e11264893
Create Date: 2024-11-20 03:22:27.140432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae075b14c2b8'
down_revision = 'b86e11264893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.drop_column('personal_note')

    # ### end Alembic commands ###
