"""Make bottler a foreign key in bottles table

Revision ID: c8413fb71e09
Revises: 199e2dc9ea1f
Create Date: 2023-09-04 14:48:33.252213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8413fb71e09'
down_revision = '199e2dc9ea1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'distillery', ['bottler_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
