"""add unique constraint on barrel_picker user_id and name

Revision ID: d636045041b4
Revises: a2518713654b
Create Date: 2026-05-22 20:59:26.592972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd636045041b4'
down_revision = 'a2518713654b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barrel_picker', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_barrel_picker_user_name', ['user_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barrel_picker', schema=None) as batch_op:
        batch_op.drop_constraint('uq_barrel_picker_user_name', type_='unique')

    # ### end Alembic commands ###
