"""Add new columns to bottle table

Revision ID: d7a2212a501d
Revises: 78a71df17691
Create Date: 2023-09-20 21:36:37.438185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7a2212a501d'
down_revision = '78a71df17691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_barrelled', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_bottled', sa.Integer(), nullable=True))
        batch_op.drop_column('year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('year_bottled')
        batch_op.drop_column('year_barrelled')
        batch_op.drop_column('size')

    # ### end Alembic commands ###
