"""widen user_login ip_address to support IPv6

Revision ID: f8d6b3ab5dd1
Revises: c5265d2758da
Create Date: 2026-05-11 17:19:35.422592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8d6b3ab5dd1'
down_revision = 'c5265d2758da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_login', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=45),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_login', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=45),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###
